spring:
  thymeleaf:    mode: HTML
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:public/
  profiles:
    active: dev

logging:
  level:
    me.kongyl.template: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
 