spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    